server:
  port: 80
  tomcat:
    max-threads: 200
    min-spare-threads: 20

# Production-specific configurations
spring:
  devtools:
    restart:
      enabled: false
  jackson:
    serialization:
      indent-output: false

# Logging configuration
logging:
  level:
    org.ganjp.blog: WARN
    org.springframework: WARN
  file:
    name: logs/gjpb.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"